version: "3"
services:
  redis-stream:
    image: redis
    entrypoint:
      - redis-server
      - --port 6379
  redis-metadata:
    image: redis
    entrypoint:
      - redis-server
      - --port 6380
  d4-server:
    build:
      context: .
      dockerfile: Dockerfile.d4-server
    image: d4-server:latest
    depends_on:
          - redis-stream
          - redis-metadata
    environment:
      - D4_REDIS_STREAM_HOST=redis-stream
      - D4_REDIS_STREAM_PORT=6379
      - D4_REDIS_METADATA_HOST=redis-metadata
      - D4_REDIS_METADATA_PORT=6380
    ports:
      - "4443:4443"
#  d4-worker_1:
#    build:
#      context: .
#      dockerfile: Dockerfile.d4-server
#    image: d4-server:latest
#    depends_on:
#          - redis-stream
#          - redis-metadata
#    environment:
#      - D4_REDIS_STREAM_HOST=redis-stream
#      - D4_REDIS_STREAM_PORT=6379
#      - D4_REDIS_METADATA_HOST=redis-metadata
#      - D4_REDIS_METADATA_PORT=6380
#    entrypoint:
#      - bash
#      - -c
#      - "cd workers/workers_1; ./workers_manager.py; read x"
  d4-web:
    build:
      context: .
      dockerfile: Dockerfile.d4-server
    image: d4-server:latest
    depends_on:
          - redis-stream
          - redis-metadata
    environment:
      - D4_REDIS_STREAM_HOST=redis-stream
      - D4_REDIS_STREAM_PORT=6379
      - D4_REDIS_METADATA_HOST=redis-metadata
      - D4_REDIS_METADATA_PORT=6380
    entrypoint:
      - bash
      - -c
      - "cd web; ./Flask_server.py; read x"
    ports:
      - "8080:7000"

